<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0;netstandard2.1</TargetFrameworks>
    <RootNamespace>Sigill.Sdk.Agent</RootNamespace>
    <AssemblyName>Sigill.Sdk.Agent</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sigill.Sdk\Sigill.Sdk.csproj" />
    <PackageReference Include="PolySharp" Version="1.14.1" PrivateAssets="all" />
  </ItemGroup>

</Project>
